### ISSUE TITLE
Protocol Error

### ISSUE THREAD

**Issue by renovat10** [spieglt/fb-delete#6]
(node:5648) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Invalid parameters url: string value expected
    at Promise (C:\Users\Renovatio\fb-delete\node_modules\puppeteer\lib\Connection.js:198:56)
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\Renovatio\fb-delete\node_modules\puppeteer\lib\
Connection.js:197:12)
    at navigate (C:\Users\Renovatio\fb-delete\node_modules\puppeteer\lib\Page.js:520:39)
    at Page.goto (C:\Users\Renovatio\fb-delete\node_modules\puppeteer\lib\Page.js:500:7)
    at followLinkByContent (C:\Users\Renovatio\fb-delete\index.js:99:14)
(node:5648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:5648) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by Pixney-William** [comment]
Got this issue too!

**Comment by lotus42** [comment]
This is due to the reason commented here: https://github.com/spieglt/fb-delete/issues/1#issuecomment-388605721

It looks for tags with exact names of years, and for the current year, those tags are different.

As a **really dirty** temporary fix so I could delete my posts, I manually added some lines to prompts.js like this, right below the loop where it adds the years.

```
years.push("This Month"); 
years.push("January " + currentYear.toString()); 
years.push("February " + currentYear.toString());
years.push("March " + currentYear.toString());
years.push("April " + currentYear.toString());
```

Also, some of the available forks (like https://github.com/alexjyong/FaceSpace-Cleaner) might address this already in a better way.

**Comment by inwardgarden** [comment]
Deleted my earlier comment because my quick-and-dirty solution still did not work for the current month, for some reason.

The reason it fails on current year stuff is due to https://github.com/spieglt/fb-delete/issues/1#issuecomment-388605721

**Comment by jackmahoney** [comment]
Does not work

**Comment by spieglt** [comment]
@lotus42 Sorry for the very late notice, but this should be fixed if you're still interested.
@renovat10 @Pixney-William @jackmahoney
